POST http://localhost:3001/api/user HTTP/1.1
content-type: application/json 

{
  "email": "haddykasseh.com",
  "password": "123",
  "firstname": "haddzy",
  "minit": "",
  "lastname": "kasseh"
}

###
POST http://localhost:3001/api/sale HTTP/1.1
content-type: application/json 

{
  "description": "Aspirin",
  "Quantity": 25,
  "price": 200,
  "Total": 5000,
  "userId": "63795a784e27e89bfd14a38a"
}

