POST http://localhost:3001/api/user HTTP/1.1
content-type: application/json 

{
  "email": "yahaddykasseh@gmail.com",
  "password": "haddix",
  "firstname": "ya haddy",
  "minit": "",
  "lastname": "kasseh"
}