PUT http://localhost:3001/api/user/6359101bfb5e9a4ef4fd880f
content-type: application/json

{
  "email": "ac@camariana.gm",
  "firstname": "A",
  "minit": "",
  "lastname": "Camara",
  "role": "Admin"
}

